"""
    Django settings for zookeeper_dashboard project.

    Generated by 'django-admin startproject' using Django 1.9.

    For more information on this file, see
    https://docs.djangoproject.com/en/1.9/topics/settings/

    For the full list of settings and their values, see
    https://docs.djangoproject.com/en/1.9/ref/settings/
    """

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

### ZooKeeper specific settings
ZOOKEEPER_SERVERS = "127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4dsaxue!a+c+9*5^0rk1a!d3mzly5%jg6)p&y0_nsq@)4280mh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
                  'django.contrib.contenttypes',
                  'django.contrib.sessions',
                  'django.contrib.sites',
                  'zookeeper_dashboard.zkadmin',
                  'zookeeper_dashboard.zktree',
                  ]

MIDDLEWARE_CLASSES = [
                      'django.middleware.common.CommonMiddleware',
                      'django.contrib.sessions.middleware.SessionMiddleware',
                      ]

ROOT_URLCONF = 'zookeeper_dashboard.urls'

TEMPLATES = [
             {
             'BACKEND': 'django.template.backends.django.DjangoTemplates',
             'DIRS': [],
             'APP_DIRS': True,
             'OPTIONS': {
             'context_processors': [
                                    'django.template.context_processors.debug',
                                    'django.template.context_processors.request',
                                    'django.contrib.auth.context_processors.auth',
                                    'django.contrib.messages.context_processors.messages',
                                    ],
             },
             },
             ]

WSGI_APPLICATION = 'zookeeper_dashboard.wsgi.application'



# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
